
image: node:20


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build               
    - rm -rf public               
    - mv dist public              
    - cp public/index.html public/404.html  
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'     
